<?php

namespace KITJAMBON\MembreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Option_MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Option_MembreRepository extends EntityRepository
{
}
