<?php

namespace KITJAMBON\MembreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParrainageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParrainageRepository extends EntityRepository
{
}
