parameters:
#    nacder_platform.example.class: nacder\PlatformBundle\Example

services:
#    nacder_platform.example:
#        class: %nacder_platform.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
