parameters:
#    kitjambon_membre.example.class: KITJAMBON\MembreBundle\Example

services:
#    kitjambon_membre.example:
#        class: %kitjambon_membre.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
