parameters:
#    kitjambon_comment.example.class: KITJAMBON\CommentBundle\Example

services:
#    kitjambon_comment.example:
#        class: %kitjambon_comment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
