<?php

namespace Proxies\__CG__\KITJAMBON\MembreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Parrainage extends \KITJAMBON\MembreBundle\Entity\Parrainage implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Parrainage' . "\0" . 'parrainageId', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Parrainage' . "\0" . 'parrainageMailFillot', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Parrainage' . "\0" . 'parrainageDate', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Parrainage' . "\0" . 'parrainageValide', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Parrainage' . "\0" . 'parrainageToken', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Parrainage' . "\0" . 'parrain', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Parrainage' . "\0" . 'fillot');
        }

        return array('__isInitialized__', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Parrainage' . "\0" . 'parrainageId', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Parrainage' . "\0" . 'parrainageMailFillot', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Parrainage' . "\0" . 'parrainageDate', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Parrainage' . "\0" . 'parrainageValide', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Parrainage' . "\0" . 'parrainageToken', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Parrainage' . "\0" . 'parrain', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Parrainage' . "\0" . 'fillot');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Parrainage $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setParrainageId($parrainageId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParrainageId', array($parrainageId));

        return parent::setParrainageId($parrainageId);
    }

    /**
     * {@inheritDoc}
     */
    public function getParrainageId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getParrainageId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParrainageId', array());

        return parent::getParrainageId();
    }

    /**
     * {@inheritDoc}
     */
    public function setParrainageMailFillot($parrainageMailFillot)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParrainageMailFillot', array($parrainageMailFillot));

        return parent::setParrainageMailFillot($parrainageMailFillot);
    }

    /**
     * {@inheritDoc}
     */
    public function getParrainageMailFillot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParrainageMailFillot', array());

        return parent::getParrainageMailFillot();
    }

    /**
     * {@inheritDoc}
     */
    public function setParrainageDate($parrainageDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParrainageDate', array($parrainageDate));

        return parent::setParrainageDate($parrainageDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getParrainageDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParrainageDate', array());

        return parent::getParrainageDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setParrainageValide($parrainageValide)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParrainageValide', array($parrainageValide));

        return parent::setParrainageValide($parrainageValide);
    }

    /**
     * {@inheritDoc}
     */
    public function getParrainageValide()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParrainageValide', array());

        return parent::getParrainageValide();
    }

    /**
     * {@inheritDoc}
     */
    public function setParrainageToken($parrainageToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParrainageToken', array($parrainageToken));

        return parent::setParrainageToken($parrainageToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getParrainageToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParrainageToken', array());

        return parent::getParrainageToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setParrain($parrain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParrain', array($parrain));

        return parent::setParrain($parrain);
    }

    /**
     * {@inheritDoc}
     */
    public function getParrain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParrain', array());

        return parent::getParrain();
    }

    /**
     * {@inheritDoc}
     */
    public function setFillot($fillot)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFillot', array($fillot));

        return parent::setFillot($fillot);
    }

    /**
     * {@inheritDoc}
     */
    public function getFillot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFillot', array());

        return parent::getFillot();
    }

}
