<?php

namespace Proxies\__CG__\KITJAMBON\MembreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Signalement extends \KITJAMBON\MembreBundle\Entity\Signalement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Signalement' . "\0" . 'signalementId', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Signalement' . "\0" . 'signalementType', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Signalement' . "\0" . 'signalementMessage', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Signalement' . "\0" . 'signalementDate', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Signalement' . "\0" . 'userId');
        }

        return array('__isInitialized__', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Signalement' . "\0" . 'signalementId', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Signalement' . "\0" . 'signalementType', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Signalement' . "\0" . 'signalementMessage', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Signalement' . "\0" . 'signalementDate', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Signalement' . "\0" . 'userId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Signalement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setSignalementId($signalementId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSignalementId', array($signalementId));

        return parent::setSignalementId($signalementId);
    }

    /**
     * {@inheritDoc}
     */
    public function getSignalementId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSignalementId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignalementId', array());

        return parent::getSignalementId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSignalementType($signalementType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSignalementType', array($signalementType));

        return parent::setSignalementType($signalementType);
    }

    /**
     * {@inheritDoc}
     */
    public function getSignalementType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignalementType', array());

        return parent::getSignalementType();
    }

    /**
     * {@inheritDoc}
     */
    public function setSignalementMessage($signalementMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSignalementMessage', array($signalementMessage));

        return parent::setSignalementMessage($signalementMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getSignalementMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignalementMessage', array());

        return parent::getSignalementMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setSignalementDate($signalementDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSignalementDate', array($signalementDate));

        return parent::setSignalementDate($signalementDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSignalementDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignalementDate', array());

        return parent::getSignalementDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', array($userId));

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', array());

        return parent::getUserId();
    }

}
