<?php

namespace Proxies\__CG__\KITJAMBON\MembreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Grade extends \KITJAMBON\MembreBundle\Entity\Grade implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Grade' . "\0" . 'gradeId', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Grade' . "\0" . 'gradeNom', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Grade' . "\0" . 'gradeAbrege', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Grade' . "\0" . 'gradeNdPoint');
        }

        return array('__isInitialized__', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Grade' . "\0" . 'gradeId', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Grade' . "\0" . 'gradeNom', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Grade' . "\0" . 'gradeAbrege', '' . "\0" . 'KITJAMBON\\MembreBundle\\Entity\\Grade' . "\0" . 'gradeNdPoint');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Grade $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setGradeId($gradeId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGradeId', array($gradeId));

        return parent::setGradeId($gradeId);
    }

    /**
     * {@inheritDoc}
     */
    public function getGradeId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getGradeId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGradeId', array());

        return parent::getGradeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setGradeNom($gradeNom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGradeNom', array($gradeNom));

        return parent::setGradeNom($gradeNom);
    }

    /**
     * {@inheritDoc}
     */
    public function getGradeNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGradeNom', array());

        return parent::getGradeNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setGradeAbrege($gradeAbrege)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGradeAbrege', array($gradeAbrege));

        return parent::setGradeAbrege($gradeAbrege);
    }

    /**
     * {@inheritDoc}
     */
    public function getGradeAbrege()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGradeAbrege', array());

        return parent::getGradeAbrege();
    }

    /**
     * {@inheritDoc}
     */
    public function setGradeNdPoint($gradeNdPoint)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGradeNdPoint', array($gradeNdPoint));

        return parent::setGradeNdPoint($gradeNdPoint);
    }

    /**
     * {@inheritDoc}
     */
    public function getGradeNdPoint()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGradeNdPoint', array());

        return parent::getGradeNdPoint();
    }

}
