parameters:
#    kitjambon_transfert.example.class: KITJAMBON\TransfertBundle\Example

services:
#    kitjambon_transfert.example:
#        class: %kitjambon_transfert.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
