kitjambon_site_menu_main:
    path:     /menu/main
    defaults: { _controller: KITJAMBONSiteBundle:Menu:main}
kitjambon_site_accueil:
    path:     / 
    defaults: { _controller: KITJAMBONSiteBundle:Accueil:index }
kitjambon_site_accueil2:
    path:     /accueil
    defaults: { _controller: KITJAMBONSiteBundle:Accueil:index}
kitjambon_site_presentation:
    path:     /accueil/persentation
    defaults: { _controller: KITJAMBONSiteBundle:Accueil:index}
kitjambon_site_cours_index:
    path:     /cours
    defaults: { _controller: KITJAMBONSiteBundle:Cours:index}
kitjambon_site_cours_view:
    path:     /cours/view/{eix}
    defaults: { _controller: KITJAMBONSiteBundle:Cours:view}
    requirements:  
        eix: \d{1}



