parameters:
#    kitjambon_site.example.class: KITJAMBON\SiteBundle\Example

services:
#    kitjambon_site.example:
#        class: %kitjambon_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
